### ISSUE TITLE
search results / style gets corrupted at random?

### ISSUE THREAD

**Issue by turmoggy** [unzan/TerribleName#14]
Search Results  http://i.imgur.com/oGpZaby.png

Random style error?  http://i.imgur.com/ju1JjsV.png  (If i hit refresh it corrects itself)

Refreshed same page  http://i.imgur.com/jyyjnAu.png

**Comment by unzan** [comment]
I couldn't reproduce the style error on that post or any other post from search results. What browser are you using? Are you using other userstyles for reddit?

For the search results page itself, I suggest enabling [Legacy Search][1] in your preference. The new search results page is garbage. Reddit admins have promised to improve it by bringing back hide/report and moderation buttons since it was still in beta (about 3 months ago) but they never did. Instead, they rolled it out of beta and then ignored [all the negative feedbacks][2]. This makes me not want to do anything with it (sorry for the rant).


[1]: https://www.reddit.com/prefs#legacy_search
[2]: https://www.reddit.com/r/changelog/comments/3bsm11/reddit_change_new_search_results_page/

**Comment by turmoggy** [comment]
I agree legacy search is better and I switched to that. Seems fine now.
